; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover



[Base]
text               = cad3f5 ; Text
subtext            = b8c0e0 ; Subtext1
sidebar-text       = cad3f5 ; Text
main               = 24273a ; Base
sidebar            = 1e2030 ; Mantle
player             = 24273a ; Base
card               = 24273a ; Base
shadow             = 1e2030 ; Mantle
selected-row       = 939ab7 ; Overlay2
button             = 8087a2 ; Overlay1
button-active      = 939ab7 ; Overlay2
button-disabled    = 6e738d ; Overlay0
tab-active         = 363a4f ; Surface0
notification       = 363a4f ; Surface0
notification-error = ed8796 ; Red
misc               = 494d64 ; Surface1
